export enum OrderStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  ACCOUNTING = "ACCOUNTING",
  KITCHEN = "KITCHEN",
  DELIVERY = "DELIVERY",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED"
}