version: "3.9"

services:
  backend:
    build: .
    container_name: webhook-backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:123@postgres:5432/restaurant_event
      - JWT_SECRET=my_super_secret_key
      - WEBHOOK_SECRET=my_super_secret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  worker-order:
    build: .
    container_name: webhook-worker-order
    command: npm run worker:order
    environment:
      - DATABASE_URL=postgresql://postgres:123@postgres:5432/restaurant_event
      - JWT_SECRET=my_super_secret_key
      - WEBHOOK_SECRET=my_super_secret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  worker-accounting:
    build: .
    container_name: webhook-worker-accounting
    command: npm run worker:accounting
    environment:
      - DATABASE_URL=postgresql://postgres:123@postgres:5432/restaurant_event
      - JWT_SECRET=my_super_secret_key
      - WEBHOOK_SECRET=my_super_secret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  worker-kitchen:
    build: .
    container_name: webhook-worker-kitchen
    command: npm run worker:kitchen
    environment:
      - DATABASE_URL=postgresql://postgres:123@postgres:5432/restaurant_event
      - JWT_SECRET=my_super_secret_key
      - WEBHOOK_SECRET=my_super_secret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  worker-delivery:
    build: .
    container_name: webhook-worker-delivery
    command: npm run worker:delivery
    environment:
      - DATABASE_URL=postgresql://postgres:123@postgres:5432/restaurant_event
      - JWT_SECRET=my_super_secret_key
      - WEBHOOK_SECRET=my_super_secret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=restaurant_event
    ports:
      - "5432:5432"   # port على جهازك لتجنب conflict مع Postgres المحلي
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
  postgres-data: